# [PROJECT_DIR]/dynotest/Cargo.toml
[package]
name = "dynotest_app"
description = "Dynotest GUI Application"
version = "0.0.1"
authors = ["Rizal Achmad Pahlevi <rizal.ahmadp@gmail.com>"]
edition = "2021"
readme = "README.md"
repository = "https://github.com/dynotestpolije/dyno_app"

[features]
default = ["images"]
images = ["dep:image"]
use_plotter = ["dep:plotters"]
barcodes = ["dep:barcoders", "dep:datamatrix", "dep:qrcode"]
dbg_log  = []


[dependencies]
serde       = { version = "1", features = ["derive"] }
bytes       = { version = "1" }
directories = { version = "5" }

itertools   = { version = "0.10" }
serialport  = { version = "4.2"  }
lazy_static = { version = "1.4" }

[dependencies.eframe]
path = "egui/crates/eframe"
default-features = true
features = ["persistence", "dark-light"]

[dependencies.dyno_types]
# if in release change to git url main branch
# git = "https://github.com/dynotestpolije/dyno_types.git"
# branch = "main" 
path = "../dyno_types"
features = ["frontend"]

[dependencies.rfd]
version = "0.11"
# default-features = false
# features = ["xdg-portal"]

[dependencies.log4rs]
version = "1.2"
default-features = false
features = [
    "rolling_file_appender",
    "background_rotation",
    "compound_policy",
    "size_trigger",
    "delete_roller"
]

[dependencies.barcoders]
version = "1.0"
optional = true

[dependencies.datamatrix]
version = "0.3"
optional = true
default-features = false

[dependencies.qrcode]
version = "0.12"
optional = true
default-features = false

[dependencies.plotters]
version = "0.3"
optional = true

[dependencies.image]
version = "0.24"
optional = true



